
Vagrant.configure("2") do |config|
 
 #Provision Domain Controller
 
 config.vm.define "dc" do |cfg| 
  config.vm.box = "../Boxes/windows_2016_virtualbox.box"
  cfg.vm.hostname = "dc"
  cfg.vm.boot_timeout = 600
  cfg.winrm.transport = :plaintext
  cfg.vm.communicator = "winrm"
  cfg.winrm.basic_auth_only = true
  cfg.winrm.timeout = 300
  cfg.winrm.retry_limit = 20
  
  #Set IP address details
  
  cfg.vm.network :private_network, ip: "192.168.38.2", gateway: "192.168.38.1"
  
   #Run Provisioning scripts
  
  cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
  cfg.vm.provision "reload"
  cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
  cfg.vm.provision "shell", path: "scripts/install-utilities.ps1", privileged: true
  cfg.vm.provision "shell", path: "scripts/configure-ou.ps1", privileged: true
  cfg.vm.provision "shell", path: "scripts/configure-AuditingPolicyGPOs.ps1", privileged: true
 
  cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", 2048]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end

 #Provision 2nd Server VM
 
 config.vm.define "svr1" do |cfg| 
  config.vm.box = "../Boxes/windows_2016_virtualbox.box"
  cfg.vm.hostname = "svr1"
  cfg.vm.boot_timeout = 600
  cfg.winrm.transport = :plaintext
  cfg.vm.communicator = "winrm"
  cfg.winrm.basic_auth_only = true
  cfg.winrm.timeout = 300
  cfg.winrm.retry_limit = 20
  cfg.vm.network :private_network, ip: "192.168.38.3", gateway: "192.168.38.1"
  
  
  #Run Provisioning scripts

  cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
  cfg.vm.provision "reload"
  cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
  cfg.vm.provision "shell", path: "scripts/install-utilities.ps1", privileged: true
 
  cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", 2048]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end

 #Provision Windows 10 Domain Client
 
 config.vm.define "win10" do |cfg|
    cfg.vm.box = "../Boxes/windows_10_virtualbox.box"
    cfg.vm.hostname = "win10"
    cfg.vm.communicator = "winrm"
    cfg.winrm.basic_auth_only = true
    cfg.winrm.timeout = 300
    cfg.winrm.retry_limit = 20
    cfg.vm.network :private_network, ip: "192.168.38.5", gateway: "192.168.38.1", dns: "192.168.38.2"
  
    #Run Provisioning scripts

    cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
    cfg.vm.provision "reload"
    cfg.vm.provision "shell", path: "scripts/provision.ps1", privileged: false
    cfg.vm.provision "shell", path: "scripts/MakeWindows10GreatAgain.ps1", privileged: true
    cfg.vm.provision "shell", path: "scripts/install-utilities.ps1", privileged: true
 
    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.customize ["modifyvm", :id, "--memory", 2048]
      vb.customize ["modifyvm", :id, "--cpus", 2]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
end

end
